### ISSUE TITLE
config file should not contain user/project specific parameters

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/gatk4-HaplotypeCaller-nf#2]
This sounds a bit weird: https://github.com/IARCbioinfo/gatk4-HaplotypeCaller-nf/blob/master/nextflow.config#L18

Generally I think a pipeline config file should contain what is specific to its corresponding pipeline (container, cpu, memory etc.) or what is specific for this pipeline on a specific cluster (module names) but not the general config of a cluster that is common to all pipelines. This should be in the `$HOME/.nextflow/config`. That's a general design choice we should discuss and use in all our pipelines. @tdelhomme is working on that at the moment.

**Comment by valleem** [comment]
100% agree that this line is project-dependent and not cluster-dependent. It is modified now.

**Comment by valleem** [comment]
And also, I look forward reading @tdelhomme guidelines about config parameter scopes.
